"""add accounting core

Revision ID: e41cfb42b8b1
Revises: 
Create Date: 2026-09-05 15:04:56.191485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e41cfb42b8b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.Enum('ASSET', 'BANK', 'CASH', 'LIABILITY', 'CAPITAL', 'INCOME', 'EXPENSE', 'OTHER_EXPENSE', name='accounttype', native_enum=False), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_code'), 'accounts', ['code'], unique=True)
    op.create_index(op.f('ix_accounts_is_archived'), 'accounts', ['is_archived'], unique=False)
    op.create_index(op.f('ix_accounts_type'), 'accounts', ['type'], unique=False)
    op.create_table('analytic_accounts',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.Enum('INCOME', 'EXPENSE', name='analytictype', native_enum=False), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytic_accounts_is_archived'), 'analytic_accounts', ['is_archived'], unique=False)
    op.create_index(op.f('ix_analytic_accounts_type'), 'analytic_accounts', ['type'], unique=False)
    op.create_table('number_sequences',
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('next_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('product_categories',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_product_categories_is_archived'), 'product_categories', ['is_archived'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('contacts',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.Enum('CUSTOMER', 'VENDOR', 'BOTH', name='contacttype', native_enum=False), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('address_street', sa.String(length=180), nullable=True),
    sa.Column('address_city', sa.String(length=80), nullable=True),
    sa.Column('address_state', sa.String(length=80), nullable=True),
    sa.Column('address_country', sa.String(length=80), nullable=False),
    sa.Column('address_pincode', sa.String(length=10), nullable=True),
    sa.Column('image_url', sa.String(length=400), nullable=True),
    sa.Column('receivable_account_id', sa.String(length=36), nullable=True),
    sa.Column('payable_account_id', sa.String(length=36), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payable_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['receivable_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_contacts_created_at', 'contacts', ['created_at'], unique=False)
    op.create_index(op.f('ix_contacts_is_archived'), 'contacts', ['is_archived'], unique=False)
    op.create_index('ix_contacts_name', 'contacts', ['name'], unique=False)
    op.create_index(op.f('ix_contacts_type'), 'contacts', ['type'], unique=False)
    op.create_table('journals',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('type', sa.Enum('SALES', 'PURCHASE', 'BANK', 'CASH', 'MISC', name='journaltype', native_enum=False), nullable=False),
    sa.Column('default_debit_account_id', sa.String(length=36), nullable=True),
    sa.Column('default_credit_account_id', sa.String(length=36), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['default_credit_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['default_debit_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journals_is_archived'), 'journals', ['is_archived'], unique=False)
    op.create_index(op.f('ix_journals_type'), 'journals', ['type'], unique=False)
    op.create_table('products',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('type', sa.Enum('GOODS', 'SERVICE', 'COMBO', name='producttype', native_enum=False), nullable=False),
    sa.Column('sales_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('sales_tax_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('income_account_id', sa.String(length=36), nullable=True),
    sa.Column('expense_account_id', sa.String(length=36), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('cost_price >= 0', name='ck_products_cost_price_nonneg'),
    sa.CheckConstraint('sales_price >= 0', name='ck_products_sales_price_nonneg'),
    sa.CheckConstraint('sales_tax_pct >= 0 AND sales_tax_pct <= 100', name='ck_products_tax_pct_range'),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.ForeignKeyConstraint(['expense_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['income_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index('ix_products_cost_price', 'products', ['cost_price'], unique=False)
    op.create_index(op.f('ix_products_is_archived'), 'products', ['is_archived'], unique=False)
    op.create_index('ix_products_name', 'products', ['name'], unique=False)
    op.create_index('ix_products_sales_price', 'products', ['sales_price'], unique=False)
    op.create_index(op.f('ix_products_type'), 'products', ['type'], unique=False)
    op.create_table('budgets',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('responsible_id', sa.String(length=36), nullable=True),
    sa.Column('state', sa.Enum('DRAFT', 'CONFIRMED', 'REVISED', 'CANCELLED', name='budgetstate', native_enum=False), nullable=False),
    sa.Column('revision_of_id', sa.String(length=36), nullable=True),
    sa.Column('revised_with_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('period_end > period_start', name='ck_budgets_period_valid'),
    sa.ForeignKeyConstraint(['responsible_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['revised_with_id'], ['budgets.id'], ),
    sa.ForeignKeyConstraint(['revision_of_id'], ['budgets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgets_state'), 'budgets', ['state'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('vendor_id', sa.String(length=36), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'BILLED', 'CANCELLED', name='purchaseorderstatus', native_enum=False), nullable=False),
    sa.Column('untaxed_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_purchase_orders_order_date'), 'purchase_orders', ['order_date'], unique=False)
    op.create_index(op.f('ix_purchase_orders_status'), 'purchase_orders', ['status'], unique=False)
    op.create_index('ix_purchase_orders_status_date', 'purchase_orders', ['status', 'order_date'], unique=False)
    op.create_index(op.f('ix_purchase_orders_vendor_id'), 'purchase_orders', ['vendor_id'], unique=False)
    op.create_table('sales_orders',
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'INVOICED', 'CANCELLED', name='salesorderstatus', native_enum=False), nullable=False),
    sa.Column('untaxed_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_sales_orders_customer_id'), 'sales_orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sales_orders_order_date'), 'sales_orders', ['order_date'], unique=False)
    op.create_index(op.f('ix_sales_orders_status'), 'sales_orders', ['status'], unique=False)
    op.create_index('ix_sales_orders_status_date', 'sales_orders', ['status', 'order_date'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('login_id', sa.String(length=12), nullable=True),
    sa.Column('contact_id', sa.String(length=36), nullable=True),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('login_id IS NULL OR (length(login_id) >= 6 AND length(login_id) <= 12)', name='ck_users_login_id_length'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login_id')
    )
    op.create_index(op.f('ix_users_contact_id'), 'users', ['contact_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('entity_name', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_name'), 'audit_logs', ['entity_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('budget_lines',
    sa.Column('budget_id', sa.String(length=36), nullable=False),
    sa.Column('analytic_account_id', sa.String(length=36), nullable=False),
    sa.Column('committed_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('committed_amount >= 0', name='ck_budget_lines_committed_nonneg'),
    sa.ForeignKeyConstraint(['analytic_account_id'], ['analytic_accounts.id'], ),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('budget_id', 'analytic_account_id', name='uq_budget_lines_analytic')
    )
    op.create_index(op.f('ix_budget_lines_analytic_account_id'), 'budget_lines', ['analytic_account_id'], unique=False)
    op.create_index(op.f('ix_budget_lines_budget_id'), 'budget_lines', ['budget_id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('entry_number', sa.String(length=32), nullable=False),
    sa.Column('journal_id', sa.String(length=36), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('state', sa.Enum('DRAFT', 'POSTED', 'REVERSED', name='entrystate', native_enum=False), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('reversal_of_id', sa.String(length=36), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_by_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ),
    sa.ForeignKeyConstraint(['posted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reversal_of_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_number')
    )
    op.create_index(op.f('ix_journal_entries_entry_date'), 'journal_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_journal_entries_journal_id'), 'journal_entries', ['journal_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_source_id'), 'journal_entries', ['source_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_source_type'), 'journal_entries', ['source_type'], unique=False)
    op.create_index(op.f('ix_journal_entries_state'), 'journal_entries', ['state'], unique=False)
    op.create_index('ix_journal_entries_state_date', 'journal_entries', ['state', 'entry_date'], unique=False)
    op.create_index('uq_journal_entries_source_live', 'journal_entries', ['source_type', 'source_id'], unique=True, sqlite_where=sa.text("state != 'REVERSED'"), postgresql_where=sa.text("state != 'REVERSED'"))
    op.create_table('notifications',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('purchase_order_lines',
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('analytic_account_id', sa.String(length=36), nullable=True),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_purchase_order_lines_quantity_positive'),
    sa.CheckConstraint('tax_pct >= 0 AND tax_pct <= 100', name='ck_purchase_order_lines_tax_pct_range'),
    sa.CheckConstraint('unit_price >= 0', name='ck_purchase_order_lines_unit_price_nonneg'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['analytic_account_id'], ['analytic_accounts.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_lines_analytic_account_id'), 'purchase_order_lines', ['analytic_account_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_lines_order_id'), 'purchase_order_lines', ['order_id'], unique=False)
    op.create_table('sales_order_lines',
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('analytic_account_id', sa.String(length=36), nullable=True),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_sales_order_lines_quantity_positive'),
    sa.CheckConstraint('tax_pct >= 0 AND tax_pct <= 100', name='ck_sales_order_lines_tax_pct_range'),
    sa.CheckConstraint('unit_price >= 0', name='ck_sales_order_lines_unit_price_nonneg'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['analytic_account_id'], ['analytic_accounts.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['sales_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_order_lines_analytic_account_id'), 'sales_order_lines', ['analytic_account_id'], unique=False)
    op.create_index(op.f('ix_sales_order_lines_order_id'), 'sales_order_lines', ['order_id'], unique=False)
    op.create_table('customer_invoices',
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('so_id', sa.String(length=36), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'PARTIAL', 'PAID', 'CANCELLED', name='customerinvoicestatus', native_enum=False), nullable=False),
    sa.Column('untaxed_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('journal_entry_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['so_id'], ['sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_customer_invoices_customer_id'), 'customer_invoices', ['customer_id'], unique=False)
    op.create_index('ix_customer_invoices_due_date', 'customer_invoices', ['due_date'], unique=False)
    op.create_index(op.f('ix_customer_invoices_invoice_date'), 'customer_invoices', ['invoice_date'], unique=False)
    op.create_index(op.f('ix_customer_invoices_so_id'), 'customer_invoices', ['so_id'], unique=False)
    op.create_index(op.f('ix_customer_invoices_status'), 'customer_invoices', ['status'], unique=False)
    op.create_index('ix_customer_invoices_status_date', 'customer_invoices', ['status', 'invoice_date'], unique=False)
    op.create_table('journal_lines',
    sa.Column('entry_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('analytic_account_id', sa.String(length=36), nullable=True),
    sa.Column('partner_id', sa.String(length=36), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('debit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('NOT (debit > 0 AND credit > 0)', name='ck_journal_lines_one_sided'),
    sa.CheckConstraint('debit > 0 OR credit > 0', name='ck_journal_lines_not_empty'),
    sa.CheckConstraint('debit >= 0 AND credit >= 0', name='ck_journal_lines_nonneg'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['analytic_account_id'], ['analytic_accounts.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_lines_account_id'), 'journal_lines', ['account_id'], unique=False)
    op.create_index(op.f('ix_journal_lines_analytic_account_id'), 'journal_lines', ['analytic_account_id'], unique=False)
    op.create_index(op.f('ix_journal_lines_entry_id'), 'journal_lines', ['entry_id'], unique=False)
    op.create_index(op.f('ix_journal_lines_partner_id'), 'journal_lines', ['partner_id'], unique=False)
    op.create_table('vendor_bills',
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('po_id', sa.String(length=36), nullable=True),
    sa.Column('vendor_id', sa.String(length=36), nullable=False),
    sa.Column('bill_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'PARTIAL', 'PAID', 'CANCELLED', name='vendorbillstatus', native_enum=False), nullable=False),
    sa.Column('untaxed_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('journal_entry_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_vendor_bills_bill_date'), 'vendor_bills', ['bill_date'], unique=False)
    op.create_index(op.f('ix_vendor_bills_due_date'), 'vendor_bills', ['due_date'], unique=False)
    op.create_index(op.f('ix_vendor_bills_po_id'), 'vendor_bills', ['po_id'], unique=False)
    op.create_index(op.f('ix_vendor_bills_status'), 'vendor_bills', ['status'], unique=False)
    op.create_index('ix_vendor_bills_status_date', 'vendor_bills', ['status', 'bill_date'], unique=False)
    op.create_index(op.f('ix_vendor_bills_vendor_id'), 'vendor_bills', ['vendor_id'], unique=False)
    op.create_table('customer_invoice_lines',
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('analytic_account_id', sa.String(length=36), nullable=True),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_customer_invoice_lines_quantity_positive'),
    sa.CheckConstraint('tax_pct >= 0 AND tax_pct <= 100', name='ck_customer_invoice_lines_tax_pct_range'),
    sa.CheckConstraint('unit_price >= 0', name='ck_customer_invoice_lines_unit_price_nonneg'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['analytic_account_id'], ['analytic_accounts.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['customer_invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_invoice_lines_analytic_account_id'), 'customer_invoice_lines', ['analytic_account_id'], unique=False)
    op.create_index(op.f('ix_customer_invoice_lines_invoice_id'), 'customer_invoice_lines', ['invoice_id'], unique=False)
    op.create_table('payments',
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('direction', sa.Enum('RECEIVE', 'SEND', name='paymentdirection', native_enum=False), nullable=False),
    sa.Column('journal_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('invoice_id', sa.String(length=36), nullable=True),
    sa.Column('bill_id', sa.String(length=36), nullable=True),
    sa.Column('journal_entry_id', sa.String(length=36), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('(invoice_id IS NULL) <> (bill_id IS NULL)', name='ck_payments_exactly_one_target'),
    sa.CheckConstraint('amount > 0', name='ck_payments_amount_positive'),
    sa.ForeignKeyConstraint(['bill_id'], ['vendor_bills.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['customer_invoices.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_payments_bill_id'), 'payments', ['bill_id'], unique=False)
    op.create_index(op.f('ix_payments_contact_id'), 'payments', ['contact_id'], unique=False)
    op.create_index(op.f('ix_payments_direction'), 'payments', ['direction'], unique=False)
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_date'), 'payments', ['payment_date'], unique=False)
    op.create_table('vendor_bill_lines',
    sa.Column('bill_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('analytic_account_id', sa.String(length=36), nullable=True),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_vendor_bill_lines_quantity_positive'),
    sa.CheckConstraint('tax_pct >= 0 AND tax_pct <= 100', name='ck_vendor_bill_lines_tax_pct_range'),
    sa.CheckConstraint('unit_price >= 0', name='ck_vendor_bill_lines_unit_price_nonneg'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['analytic_account_id'], ['analytic_accounts.id'], ),
    sa.ForeignKeyConstraint(['bill_id'], ['vendor_bills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_bill_lines_analytic_account_id'), 'vendor_bill_lines', ['analytic_account_id'], unique=False)
    op.create_index(op.f('ix_vendor_bill_lines_bill_id'), 'vendor_bill_lines', ['bill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_bill_lines_bill_id'), table_name='vendor_bill_lines')
    op.drop_index(op.f('ix_vendor_bill_lines_analytic_account_id'), table_name='vendor_bill_lines')
    op.drop_table('vendor_bill_lines')
    op.drop_index(op.f('ix_payments_payment_date'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_direction'), table_name='payments')
    op.drop_index(op.f('ix_payments_contact_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_bill_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_customer_invoice_lines_invoice_id'), table_name='customer_invoice_lines')
    op.drop_index(op.f('ix_customer_invoice_lines_analytic_account_id'), table_name='customer_invoice_lines')
    op.drop_table('customer_invoice_lines')
    op.drop_index(op.f('ix_vendor_bills_vendor_id'), table_name='vendor_bills')
    op.drop_index('ix_vendor_bills_status_date', table_name='vendor_bills')
    op.drop_index(op.f('ix_vendor_bills_status'), table_name='vendor_bills')
    op.drop_index(op.f('ix_vendor_bills_po_id'), table_name='vendor_bills')
    op.drop_index(op.f('ix_vendor_bills_due_date'), table_name='vendor_bills')
    op.drop_index(op.f('ix_vendor_bills_bill_date'), table_name='vendor_bills')
    op.drop_table('vendor_bills')
    op.drop_index(op.f('ix_journal_lines_partner_id'), table_name='journal_lines')
    op.drop_index(op.f('ix_journal_lines_entry_id'), table_name='journal_lines')
    op.drop_index(op.f('ix_journal_lines_analytic_account_id'), table_name='journal_lines')
    op.drop_index(op.f('ix_journal_lines_account_id'), table_name='journal_lines')
    op.drop_table('journal_lines')
    op.drop_index('ix_customer_invoices_status_date', table_name='customer_invoices')
    op.drop_index(op.f('ix_customer_invoices_status'), table_name='customer_invoices')
    op.drop_index(op.f('ix_customer_invoices_so_id'), table_name='customer_invoices')
    op.drop_index(op.f('ix_customer_invoices_invoice_date'), table_name='customer_invoices')
    op.drop_index('ix_customer_invoices_due_date', table_name='customer_invoices')
    op.drop_index(op.f('ix_customer_invoices_customer_id'), table_name='customer_invoices')
    op.drop_table('customer_invoices')
    op.drop_index(op.f('ix_sales_order_lines_order_id'), table_name='sales_order_lines')
    op.drop_index(op.f('ix_sales_order_lines_analytic_account_id'), table_name='sales_order_lines')
    op.drop_table('sales_order_lines')
    op.drop_index(op.f('ix_purchase_order_lines_order_id'), table_name='purchase_order_lines')
    op.drop_index(op.f('ix_purchase_order_lines_analytic_account_id'), table_name='purchase_order_lines')
    op.drop_table('purchase_order_lines')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('uq_journal_entries_source_live', table_name='journal_entries', sqlite_where=sa.text("state != 'REVERSED'"), postgresql_where=sa.text("state != 'REVERSED'"))
    op.drop_index('ix_journal_entries_state_date', table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_state'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_source_type'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_source_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_journal_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_entry_date'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_budget_lines_budget_id'), table_name='budget_lines')
    op.drop_index(op.f('ix_budget_lines_analytic_account_id'), table_name='budget_lines')
    op.drop_table('budget_lines')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_contact_id'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_sales_orders_status_date', table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_status'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_order_date'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_customer_id'), table_name='sales_orders')
    op.drop_table('sales_orders')
    op.drop_index(op.f('ix_purchase_orders_vendor_id'), table_name='purchase_orders')
    op.drop_index('ix_purchase_orders_status_date', table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_status'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_order_date'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_budgets_state'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_products_type'), table_name='products')
    op.drop_index('ix_products_sales_price', table_name='products')
    op.drop_index('ix_products_name', table_name='products')
    op.drop_index(op.f('ix_products_is_archived'), table_name='products')
    op.drop_index('ix_products_cost_price', table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_journals_type'), table_name='journals')
    op.drop_index(op.f('ix_journals_is_archived'), table_name='journals')
    op.drop_table('journals')
    op.drop_index(op.f('ix_contacts_type'), table_name='contacts')
    op.drop_index('ix_contacts_name', table_name='contacts')
    op.drop_index(op.f('ix_contacts_is_archived'), table_name='contacts')
    op.drop_index('ix_contacts_created_at', table_name='contacts')
    op.drop_table('contacts')
    op.drop_table('roles')
    op.drop_index(op.f('ix_product_categories_is_archived'), table_name='product_categories')
    op.drop_table('product_categories')
    op.drop_table('number_sequences')
    op.drop_index(op.f('ix_analytic_accounts_type'), table_name='analytic_accounts')
    op.drop_index(op.f('ix_analytic_accounts_is_archived'), table_name='analytic_accounts')
    op.drop_table('analytic_accounts')
    op.drop_index(op.f('ix_accounts_type'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_is_archived'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_code'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
