"""add document mail tracking

Revision ID: fffe688792ce
Revises: e41cfb42b8b1
Create Date: 2026-09-05 16:16:44.971849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fffe688792ce'
down_revision: Union[str, Sequence[str], None] = 'e41cfb42b8b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_invoices', sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('customer_invoices', sa.Column('last_send_error', sa.String(length=200), nullable=True))
    op.add_column('vendor_bills', sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('vendor_bills', sa.Column('last_send_error', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_bills', 'last_send_error')
    op.drop_column('vendor_bills', 'last_sent_at')
    op.drop_column('customer_invoices', 'last_send_error')
    op.drop_column('customer_invoices', 'last_sent_at')
    # ### end Alembic commands ###
